---
- name: Установка NGINX
  ansible.builtin.package:
    name: nginx
    state: present

- name: Настройка NGINX
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/default

- name: Тест конфига NGINX
  ansible.builtin.command:
    cmd: nginx -t

- name: Перезапуск NGINX
  ansible.builtin.service:
    name: nginx
    state: restarted
